config/routes.rb
  resources :tags,   only: [:show]
  resources :emojis, only: [:show]
  resources :invites, only: [:index, :create, :destroy]
  resources :filters, except: [:show]
  resource :relationships, only: [:show, :update]

  get '/public', to: 'public_timelines#show', as: :public_timeline
  get '/media_proxy/:id/(*any)', to: 'media_proxy#show', as: :media_proxy

  resource :authorize_interaction, only: [:show, :create]
  resource :share, only: [:show, :create]

  namespace :admin do
    get '/dashboard', to: 'dashboard#index'

    resources :domain_allows, only: [:new, :create, :show, :destroy]
    resources :domain_blocks, only: [:new, :create, :show, :destroy, :update, :edit]

    resources :email_domain_blocks, only: [:index, :new, :create, :destroy]
    resources :action_logs, only: [:index]
    resources :warning_presets, except: [:new]

    resources :announcements, except: [:show] do
      member do
        post :publish
        post :unpublish
      end
    end

    resource :settings, only: [:edit, :update]
    resources :site_uploads, only: [:destroy]

    resources :invites, only: [:index, :create, :destroy] do
      collection do
        post :deactivate_all
      end
    end

    resources :relays, only: [:index, :new, :create, :destroy] do
      member do
        post :enable
        post :disable
      end
    end

    resources :instances, only: [:index, :show], constraints: { id: /[^\/]+/ }

    resources :reports, only: [:index, :show] do
      member do
        post :assign_to_self
        post :unassign
        post :reopen
        post :resolve
      end

      resources :reported_statuses, only: [:create]
    end

    resources :report_notes, only: [:create, :destroy]

    resources :accounts, only: [:index, :show, :destroy] do
      member do
        post :enable
        post :unsensitive
        post :unsilence
        post :unsuspend
        post :redownload
        post :remove_avatar
        post :remove_header
        post :memorialize
        post :approve
        post :reject
      end

      resource :change_email, only: [:show, :update]
      resource :reset, only: [:create]
      resource :action, only: [:new, :create], controller: 'account_actions'
      resources :statuses, only: [:index, :show, :create, :update, :destroy]
      resources :relationships, only: [:index]

      resource :confirmation, only: [:create] do
        collection do
          post :resend
        end
      end

      resource :role, only: [] do
        member do
          post :promote
          post :demote
        end
      end
    end

    resources :pending_accounts, only: [:index] do
      collection do
        post :approve_all
        post :reject_all
        post :batch
      end
    end

    resources :users, only: [] do
      resource :two_factor_authentication, only: [:destroy]
    end

    resources :custom_emojis, only: [:index, :new, :create] do
      collection do
        post :batch
      end
    end

    resources :ip_blocks, only: [:index, :new, :create] do
      collection do
        post :batch
      end
    end

    resources :account_moderation_notes, only: [:create, :destroy]

    resources :tags, only: [:index, :show, :update] do
      collection do
        post :approve_all
        post :reject_all
        post :batch
      end
    end
  end

  get '/admin', to: redirect('/admin/dashboard', status: 302)

  namespace :api do
    # OEmbed
    get '/oembed', to: 'oembed#show', as: :oembed

    # Identity proofs
    get :proofs, to: 'proofs#index'

    # JSON / REST API
    namespace :v1 do
      resources :statuses, only: [:create, :show, :destroy] do
        scope module: :statuses do
          resources :reblogged_by, controller: :reblogged_by_accounts, only: :index
          resources :favourited_by, controller: :favourited_by_accounts, only: :index
          resource :reblog, only: :create
          post :unreblog, to: 'reblogs#destroy'

          resource :favourite, only: :create
          post :unfavourite, to: 'favourites#destroy'

          resource :bookmark, only: :create
          post :unbookmark, to: 'bookmarks#destroy'

          resource :mute, only: :create
          post :unmute, to: 'mutes#destroy'

          resource :pin, only: :create
          post :unpin, to: 'pins#destroy'
        end

        member do
          get :context
        end
      end

      namespace :timelines do
        resource :home, only: :show, controller: :home
        resource :public, only: :show, controller: :public
        resources :tag, only: :show
        resources :list, only: :show
      end

      resources :streaming, only: [:index]
      resources :custom_emojis, only: [:index]
      resources :suggestions, only: [:index, :destroy]
      resources :scheduled_statuses, only: [:index, :show, :update, :destroy]
      resources :preferences, only: [:index]

      resources :announcements, only: [:index] do
        scope module: :announcements do
          resources :reactions, only: [:update, :destroy]
        end

        member do
          post :dismiss
        end
      end

      # namespace :crypto do
      #   resources :deliveries, only: :create

      #   namespace :keys do
      #     resource :upload, only: [:create]
      #     resource :query,  only: [:create]
      #     resource :claim,  only: [:create]
      #     resource :count,  only: [:show]
      #   end

      #   resources :encrypted_messages, only: [:index] do
      #     collection do
      #       post :clear
      #     end
      #   end
      # end

      resources :conversations, only: [:index, :destroy] do
        member do
          post :read
        end
      end

      resources :media,        only: [:create, :update, :show]
      resources :blocks,       only: [:index]
      resources :mutes,        only: [:index]
      resources :favourites,   only: [:index]
      resources :bookmarks,    only: [:index]
      resources :reports,      only: [:create]
      resources :trends,       only: [:index]
      resources :filters,      only: [:index, :create, :show, :update, :destroy]
      resources :endorsements, only: [:index]
      resources :markers,      only: [:index, :create]

      namespace :apps do
        get :verify_credentials, to: 'credentials#show'
      end

      resources :apps, only: [:create]

      resource :instance, only: [:show] do
        resources :peers, only: [:index], controller: 'instances/peers'
        resource :activity, only: [:show], controller: 'instances/activity'
      end

      resource :domain_blocks, only: [:show, :create, :destroy]
      resource :directory, only: [:show]

      resources :follow_requests, only: [:index] do
        member do
          post :authorize
          post :reject
        end
      end

      resources :notifications, only: [:index, :show] do
        collection do
          post :clear
        end

        member do
          post :dismiss
        end
      end

      namespace :accounts do
        get :verify_credentials, to: 'credentials#show'
        patch :update_credentials, to: 'credentials#update'
        resource :search, only: :show, controller: :search
        resources :relationships, only: :index
      end

      resources :accounts, only: [:create, :show] do
        resources :statuses, only: :index, controller: 'accounts/statuses'
        resources :followers, only: :index, controller: 'accounts/follower_accounts'
        resources :following, only: :index, controller: 'accounts/following_accounts'
        resources :lists, only: :index, controller: 'accounts/lists'
        resources :identity_proofs, only: :index, controller: 'accounts/identity_proofs'
        resources :featured_tags, only: :index, controller: 'accounts/featured_tags'

        member do
          post :follow
          post :unfollow
          post :block
          post :unblock
          post :mute
          post :unmute
        end

        resource :pin, only: :create, controller: 'accounts/pins'
        post :unpin, to: 'accounts/pins#destroy'
        resource :note, only: :create, controller: 'accounts/notes'
      end

      resources :lists, only: [:index, :create, :show, :update, :destroy] do
        resource :accounts, only: [:show, :create, :destroy], controller: 'lists/accounts'
      end

      namespace :featured_tags do
        get :suggestions, to: 'suggestions#index'
      end

      resources :featured_tags, only: [:index, :create, :destroy]

      resources :polls, only: [:create, :show] do
        resources :votes, only: :create, controller: 'polls/votes'
      end

      namespace :push do
        resource :subscription, only: [:create, :show, :update, :destroy]
      end

      namespace :admin do
        resources :accounts, only: [:index, :show, :destroy] do
          member do
            post :enable
            post :unsensitive
            post :unsilence
            post :unsuspend
            post :approve
            post :reject
          end

          resource :action, only: [:create], controller: 'account_actions'
        end

        resources :reports, only: [:index, :show] do
          member do
            post :assign_to_self
            post :unassign
            post :reopen
            post :resolve
          end
        end
      end
    end

    namespace :v2 do
      resources :media, only: [:create]
      get '/search', to: 'search#index', as: :search
    end

    namespace :web do
      resource :settings, only: [:update]
      resource :embed, only: [:create]
      resources :push_subscriptions, only: [:create] do
        member do
          put :update
        end
      end
    end
  end

  get '/web/(*any)', to: 'home#index', as: :web

  get '/about',        to: 'about#show'
  get '/about/more',   to: 'about#more'
  get '/terms',        to: 'about#terms'

  match '/', via: [:post, :put, :patch, :delete], to: 'application#raise_not_found', format: false

app/controllers/about_controller.rb
# frozen_string_literal: true

class AboutController < ApplicationController
  include RegistrationSpamConcern

  layout 'public'

  before_action :require_open_federation!, only: [:show, :more]
  before_action :set_body_classes, only: :show
  before_action :set_instance_presenter
  before_action :set_expires_in, only: [:more, :terms]
  before_action :set_registration_form_time, only: :show

  skip_before_action :require_functional!, only: [:more, :terms]

  def show; end

  def more
    flash.now[:notice] = I18n.t('about.instance_actor_flash') if params[:instance_actor]

    toc_generator = TOCGenerator.new(@instance_presenter.site_extended_description)

    @contents          = toc_generator.html
    @table_of_contents = toc_generator.toc
    @blocks            = DomainBlock.with_user_facing_limitations.by_severity if display_blocks?
  end

  def terms; end

  helper_method :display_blocks?
  helper_method :display_blocks_rationale?
  helper_method :public_fetch_mode?
  helper_method :new_user

  private

  def require_open_federation!
    not_found if whitelist_mode?
  end

  def display_blocks?
    Setting.show_domain_blocks == 'all' || (Setting.show_domain_blocks == 'users' && user_signed_in?)
  end

  def display_blocks_rationale?
    Setting.show_domain_blocks_rationale == 'all' || (Setting.show_domain_blocks_rationale == 'users' && user_signed_in?)
  end

  def new_user
    User.new.tap do |user|
      user.build_account
      user.build_invite_request
    end
  end

  def set_instance_presenter
    @instance_presenter = InstancePresenter.new
  end

  def set_body_classes
    @hide_navbar = true
  end

  def set_expires_in
    expires_in 0, public: true
  end
end

app/views/about/_domain_blocks.html.haml
%table
  %thead
    %tr
      %th= t('about.unavailable_content_description.domain')
      %th= t('about.unavailable_content_description.reason')
  %tbody
    - domain_blocks.each do |domain_block|
      %tr
        %td.nowrap
          %span{ title: "SHA-256: #{domain_block.domain_digest}" }= domain_block.public_domain
        %td
          = domain_block.public_comment if display_blocks_rationale?

app/views/about/_login.html.haml
= simple_form_for(new_user, url: user_session_path, namespace: 'login') do |f|
  .fields-group
    - if use_seamless_external_login?
      = f.input :email, placeholder: t('simple_form.labels.defaults.username_or_email'), input_html: { 'aria-label' => t('simple_form.labels.defaults.username_or_email') }, hint: false
    - else
      = f.input :email, placeholder: t('simple_form.labels.defaults.email'), input_html: { 'aria-label' => t('simple_form.labels.defaults.email') }, hint: false

    = f.input :password, placeholder: t('simple_form.labels.defaults.password'), input_html: { 'aria-label' => t('simple_form.labels.defaults.password') }, hint: false

  .actions
    = f.button :button, t('auth.login'), type: :submit, class: 'button button-primary'

  %p.hint.subtle-hint= link_to t('auth.trouble_logging_in'), new_user_password_path

app/views/about/_registration.html.haml
.simple_form__overlay-area{ class: (closed_registrations? && @instance_presenter.closed_registrations_message.present?) ? 'simple_form__overlay-area__blurred' : '' }
  = simple_form_for(new_user, url: user_registration_path, namespace: 'registration', html: { novalidate: false }) do |f|
    %p.lead= t('about.federation_hint_html', instance: content_tag(:strong, site_hostname))

    .fields-group
      = f.simple_fields_for :account do |account_fields|
        = account_fields.input :username, wrapper: :with_label, label: false, required: true, input_html: { 'aria-label' => t('simple_form.labels.defaults.username'), :autocomplete => 'off', placeholder: t('simple_form.labels.defaults.username'), pattern: '[a-zA-Z0-9_]+', maxlength: 30 }, append: "@#{site_hostname}", hint: false, disabled: closed_registrations?

      = f.input :email, placeholder: t('simple_form.labels.defaults.email'), required: true, input_html: { 'aria-label' => t('simple_form.labels.defaults.email'), :autocomplete => 'off' }, hint: false, disabled: closed_registrations?
      = f.input :password, placeholder: t('simple_form.labels.defaults.password'), required: true, input_html: { 'aria-label' => t('simple_form.labels.defaults.password'), :autocomplete => 'off', :minlength => User.password_length.first, :maxlength => User.password_length.last }, hint: false, disabled: closed_registrations?
      = f.input :password_confirmation, placeholder: t('simple_form.labels.defaults.confirm_password'), required: true, input_html: { 'aria-label' => t('simple_form.labels.defaults.confirm_password'), :autocomplete => 'off' }, hint: false, disabled: closed_registrations?

      = f.input :confirm_password, as: :string, placeholder: t('simple_form.labels.defaults.honeypot', label: t('simple_form.labels.defaults.password')), required: false, input_html: { 'aria-label' => t('simple_form.labels.defaults.honeypot', label: t('simple_form.labels.defaults.password')), :autocomplete => 'off' }, hint: false, disabled: closed_registrations?
      = f.input :website, as: :url, placeholder: t('simple_form.labels.defaults.honeypot', label: 'Website'), required: false, input_html: { 'aria-label' => t('simple_form.labels.defaults.honeypot', label: 'Website'), :autocomplete => 'off' }, hint: false, disabled: closed_registrations?

    - if approved_registrations?
      .fields-group
        = f.simple_fields_for :invite_request do |invite_request_fields|
          = invite_request_fields.input :text, as: :text, wrapper: :with_block_label, required: Setting.require_invite_text

    .fields-group
      = f.input :agreement, as: :boolean, wrapper: :with_label, label: t('auth.checkbox_agreement_html', rules_path: about_more_path, terms_path: terms_path), required: true, disabled: closed_registrations?

    .actions
      = f.button :button, sign_up_message, type: :submit, class: 'button button-primary', disabled: closed_registrations?

  - if closed_registrations? && @instance_presenter.closed_registrations_message.present?
    .simple_form__overlay-area__overlay
      .simple_form__overlay-area__overlay__content.rich-formatting
        .block-icon= fa_icon 'warning'
        = @instance_presenter.closed_registrations_message.html_safe

app/views/about/more.html.haml
- content_for :page_title do
  = site_hostname

- content_for :header_tags do
  = javascript_pack_tag 'public', crossorigin: 'anonymous'
  = render partial: 'shared/og'

.grid-4
  .column-0
    .public-account-header.public-account-header--no-bar
      .public-account-header__image
        = image_tag @instance_presenter.hero&.file&.url || @instance_presenter.thumbnail&.file&.url || asset_pack_path('media/images/preview.jpg'), alt: @instance_presenter.site_title, class: 'parallax'

  .column-1
    .landing-page__call-to-action{ dir: 'ltr' }
      .row
        .row__information-board
          .information-board__section
            %span= t 'about.user_count_before'
            %strong= number_to_human @instance_presenter.user_count, strip_insignificant_zeros: true
            %span= t 'about.user_count_after', count: @instance_presenter.user_count
          .information-board__section
            %span= t 'about.status_count_before'
            %strong= number_to_human @instance_presenter.status_count, strip_insignificant_zeros: true
            %span= t 'about.status_count_after', count: @instance_presenter.status_count
        .row__mascot
          .landing-page__mascot
            = image_tag @instance_presenter.mascot&.file&.url || asset_pack_path('media/images/elephant_ui_plane.svg'), alt: ''

  .column-2
    .contact-widget
      %h4= t 'about.administered_by'

      = account_link_to(@instance_presenter.contact_account)

      - if @instance_presenter.site_contact_email.present?
        %h4
          = succeed ':' do
            = t 'about.contact'

        = link_to @instance_presenter.site_contact_email, @instance_presenter.site_contact_email

  .column-3
    = render 'application/flashes'

    - if @contents.blank? && (!display_blocks? || @blocks&.empty?)
      = nothing_here
    - else
      .box-widget
        .rich-formatting
          = @contents.html_safe

          - if display_blocks? && !@blocks.empty?
            %h2#unavailable-content= t('about.unavailable_content')

            %p= t('about.unavailable_content_html')

            - if (blocks = @blocks.select(&:reject_media?)) && !blocks.empty?
              %h3= t('about.unavailable_content_description.rejecting_media_title')
              %p= t('about.unavailable_content_description.rejecting_media')
              = render partial: 'domain_blocks', locals: { domain_blocks: blocks }
            - if (blocks = @blocks.select(&:silence?)) && !blocks.empty?
              %h3= t('about.unavailable_content_description.silenced_title')
              %p= t('about.unavailable_content_description.silenced')
              = render partial: 'domain_blocks', locals: { domain_blocks: blocks }
            - if (blocks = @blocks.select(&:suspend?)) && !blocks.empty?
              %h3= t('about.unavailable_content_description.suspended_title')
              %p= t('about.unavailable_content_description.suspended')
              = render partial: 'domain_blocks', locals: { domain_blocks: blocks }

  .column-4
    %ul.table-of-contents
      - @table_of_contents.each do |item|
        %li
          = link_to item.title, "##{item.anchor}"

          - unless item.children.empty?
            %ul
              - item.children.each do |sub_item|
                %li= link_to sub_item.title, "##{sub_item.anchor}"

      - if display_blocks? && !@blocks.empty?
        %li= link_to t('about.unavailable_content'), '#unavailable-content'

app/views/about/show.html.haml
- content_for :page_title do
  = site_hostname

- content_for :header_tags do
  %link{ rel: 'canonical', href: about_url }/
  = render partial: 'shared/og'
  <link rel="stylesheet" media="all" href="https://framasoft.org/nav/lib/bootstrap/css/bootstrap.min.css" />
  <link rel="stylesheet" media="all" href="https://framasoft.org/nav/lib/fork-awesome/css/fork-awesome.min.css" />
  <script src="https://framasoft.org/nav/lib/jquery/jquery.min.js" crossorigin="anonymous"></script>
  <script src="https://framasoft.org/nav/lib/bootstrap/js/bootstrap.min.js" crossorigin="anonymous"></script>

:javascript
  jQuery(document).ready(function() {
    jQuery("#play-pause a").on('click', function() {
      if(jQuery(this).children('.glyphicon').hasClass('glyphicon-pause')) {
        jQuery(this).children('.glyphicon').addClass('glyphicon-play').removeClass('glyphicon-pause');
        jQuery(this).attr('title','Lecture');
        jQuery(this).children('.sr-only').text('Lecture');
        jQuery('#carousel-vox').carousel('pause');
      } else {
        jQuery(this).children('.glyphicon').addClass('glyphicon-pause').removeClass('glyphicon-play');
        jQuery(this).attr('title','Pause');
        jQuery(this).children('.sr-only').text('Pause');
        jQuery('#carousel-vox').carousel('cycle');
      };
      return false;
    });
    jQuery('#carousel-vox').carousel({'cycle' :true, 'interval': 7000});
  });

#internav.clearfix
  .container
    %ul.nav.navbar-nav.navbar-right
      %li
        %a{:href => "/auth/sign_in"} Se connecter
      %li
        %a{:href => "/auth/sign_up"} Créer un compte

.container.ombre
  %header{role: "banner"}
    %h1
      = link_to '<b class="violet">Frama</b><b class="vert">piaf</b>'.html_safe, "/"
      %h2.lead
        %i= "Microblogging libre et fédéré"
      %hr.trait{role: "presentation"}

  %main
    .row.hero
      .col-md-12.text-center
        #carousel-vox.carousel.slide{role: 'presentation'}
          .carousel-inner
            .item.active
              %img{src: "https://framapiaf.org/pics/piaf-01-creer-compte.jpg", alt: ""}
              .carousel-caption
                %p.h3
                  Créez votre compte et connectez-vous
            .item
              %img{src: "https://framapiaf.org/pics/piaf-03-suivre.jpg", alt: ""}
              .carousel-caption
                %p.h3
                  Recherchez et suivez vos contacts
            .item
              %img{src: "https://framapiaf.org/pics/piaf-02-publier.jpg", alt: ""}
              .carousel-caption
                %p.h3
                  et partagez avec eux vos messages
          %p#play-pause.text-center
            %a.carousel-control{href:"#play-pause",title:"Pause"}
              %i.glyphicon.glyphicon-pause
              %span.sr-only
                Pause
          <a class="left carousel-control" href="#carousel-vox" role="button" title="Diapo précédente" data-slide="prev"><i class="glyphicon glyphicon-chevron-left"></i><span class="sr-only">Diapo précédente</span></a>
          <a class="right carousel-control" href="#carousel-vox" role="button" title="Diapo suivante" data-slide="next"><i class="glyphicon glyphicon-chevron-right"></i><span class="sr-only">Diapo suivante</span></a>
        .col-md-6.text-center
          %a.btn.btn-primary.btn-lg{:href => "/auth/sign_in"}
            %i.glyphicon.glyphicon-lock
            Se connecter »
        .col-md-6.text-center
          %a.btn.btn-success.btn-lg{:href => "/auth/sign_up"}
            %i.glyphicon.glyphicon-user
            Créer un compte »
    %hr{role: "presentation"}
    .row
      #tuto-faq.col-md-4
        %h2.h2 Prise en main
        %p.text-center{:role => "presentation"}
          %span.glyphicon.glyphicon-question-sign
        %p
          <b class="violet">Frama</b><b class="vert">piaf</b> est un service de microblog similaire à Twitter.
          Il est libre, décentralisé et fédéré. Il permet de courts messages (max. 500 caractères), de définir leur degré de confidentialité
          et de suivre les membres du réseau sans publicité ni pistage.
        %p
          - if Setting.profile_directory
            Vous pouvez aussi
            = optional_link_to Setting.profile_directory, explore_path do
              explorer l'annuaire d'utilisateurs
          - if Setting.timeline_preview
            et voir
            = optional_link_to Setting.timeline_preview, public_timeline_path do
              un aperçu
            des messages publics.
        %p
          Vous trouverez un <a href="https://docs.framasoft.org/fr/mastodon/5min.html" target="_blank" rel="noopener noreferrer">guide de prise en main en 5 minutes</a> ainsi que la traduction de la <a href="https://docs.framasoft.org/fr/mastodon/" target="_blank" rel="noopener noreferrer">documentation officielle</a> de Mastodon par l’équipe <a href="https://participer.framasoft.org/traduction-rejoignez-framalang" target="_blank" rel="noopener noreferrer"><b class="violet">Frama</b><b class="rouge">lang</b></a> sur nos pages d’aide.
      #le-logiciel.col-md-4
        %h2.h2 Le logiciel
        %p.text-center{:role => "presentation"}
          %span.glyphicon.glyphicon-cloud
        %p
          <b class="violet">Frama</b><b class="vert">piaf</b> repose sur le logiciel libre
          %a{:href => "https://github.com/tootsuite/mastodon", :target => '_blank', :rel => 'noopener noreferrer'} Mastodon
        %p
          Il s’agit d’
          %a{:href => "https://joinmastodon.org", :target => '_blank', :rel => 'noopener noreferrer'} une instance parmi d'autres.
          Elle est compatible avec Pleroma, PeerTube, Friendica et toute autre logiciel qui repose sur le protocole
          %a{:href => "https://fr.wikipedia.org/wiki/ActivityPub", :target => '_blank', :rel => 'noopener noreferrer'} ActivityPub.
        %p
          Mastodon est sous
          %a{:href => "https://github.com/tootsuite/mastodon/blob/master/LICENSE", :target => '_blank', :rel => 'noopener noreferrer'}
            licence
            %abbr{:title => "GNU Affero General Public License", :target => '_blank', :rel => 'noopener noreferrer'} AGPL
        %p
          Nous vous recommandons les applications pour Android
          %a{:href => "https://play.google.com/store/apps/details?id=fr.gouv.etalab.mastodon", :target => '_blank', :rel => 'noopener noreferrer'}Fedilab
          (aussi sur
          %a{:href => "https://f-droid.org/fr/packages/fr.gouv.etalab.mastodon", :target => '_blank', :rel => 'noopener noreferrer'}F-Droid
          )
          et
          %a{:href => "https://itunes.apple.com/us/app/amaroq-for-mastodon/id1214116200?mt=8", :target => '_blank', :rel => 'noopener noreferrer'}Amaroq
          sur iOS. Vous pouvez aussi utiliser
          %a{:href => "https://joinmastodon.org/apps", :target => '_blank', :rel => 'noopener noreferrer'}d'autres applications,
          également disponibles sur d'autres plateformes.
      #jardin.col-md-4
        %h2.h2 Cultivez votre jardin
        %p.text-center{:role => "presentation"}
          %span.glyphicon.glyphicon-tree-deciduous
        %p
          Pour participer au développement du logiciel, proposer des améliorations
          ou simplement le télécharger, rendez-vous sur
          = succeed "." do
            %a{:href => "https://github.com/tootsuite/mastodon", :target => '_blank', :rel => 'noopener noreferrer'} le site de développement
        %p
          Si vous souhaitez installer ce logiciel pour votre propre usage et ainsi gagner en autonomie, nous vous aidons sur :
        %p.text-center
          %a.btn.btn-success{:href => "https://framacloud.org/fr/cultiver-son-jardin/mastodon.html", :target => '_blank', :rel => 'noopener noreferrer'}
            %i.glyphicon.glyphicon-tree-deciduous
            framacloud.org

app/views/about/terms.html.haml
- content_for :page_title do
  = t('terms.title', instance: site_hostname)

.grid
  .column-0
    .box-widget
      .rich-formatting= @instance_presenter.site_terms.html_safe.presence || t('terms.body_html')
  .column-1
    = render 'application/sidebar'